language: python

os:   linux
dist: trusty
sudo: required

python:
  - '3.6'

cache: pip

branches:
  only:
    - master

install:
  - zend-doc-theme-pt-br/bin/travis.sh

script:
  - zend-doc-theme-pt-br/bin/build.sh -t "${SITE_TITLE}"
  - mkdocs build

deploy:
  provider:     pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir:    'doc/html'
  on:
    branch: master

env:
  global:
    - SITE_TITLE="Tutoriais do Zend Framework"
